In [22]:
'''
1. Generate a 3x4 NumPy array with random integers between 1 
and 50.   
a. Calculate and print the Mean, Median, and Standard Deviation 
of the array 
b. Print the Sum of all elements and the sum of each row. 
c. Reshape the 3x4 array into a 2x6 array and print it.
'''
import numpy as np

# part-a
arr = np.random.randint(1,50,(3,4),dtype=int)
print("The original array is:",arr)
print("\n===========\n")
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print("Mean: ",mean)
print("Median: ",median)
print("Standard deviation: ",std_dev)
print("\n===========\n")

#Part-b
print("The sum of all elements is: ",np.sum(arr))
print("The sum row-wise is:",arr.sum(axis=1))
print("\n===========\n")

#Part-c
reshaped = arr.reshape(2,6)
print("The reshaped array is:",reshaped)

The original array is: [[ 4 25 44 33]
 [ 9  8 48  8]
 [20 30 23 22]]


Mean:  22.833333333333332
Median:  22.5
Standard deviation:  13.649379310267394


The sum of all elements is:  274
The sum row-wise is: [106  73  95]


The reshaped array is: [[ 4 25 44 33  9  8]
 [48  8 20 30 23 22]]


In [32]:
'''
2. Create two (3 * 3) matrices using NumPy and print it. 
Perform and print the results of the following linear algebra operations 
a. Matrix addition 
b. Matrix subtraction 
c. Matrix multiplication (element-wise and dot product) 
d. Transpose of a matrix 
e. Determinant and inverse (if applicable) 
'''
arr_1 = np.random.randint(0,10,(3,3),dtype=int)
arr_2 = np.random.randint(0,10,(3,3),dtype=int)
print("The first array is: ",arr_1)
print("")
print("The second array is: ",arr_2)
print("\n===========\n")

#Part-a
print("The sum of two matrices: ",arr_1+arr_2)
print("\n===========\n")

#Part-b
print("The difference of two matrices: ",arr_1 - arr_2)
print("\n===========\n")

#Part-c
print("Matrix multiplication:")
print("Element-wise",arr_1*arr_2)
print("")
print("Dot product:",arr_1@arr_2)
print("\n===========\n")

#Part-d
print("The transpose of the matrix arr_1 is:",arr_1.T)
print("The transpose of the matrix arr_2 is:",arr_2.T)
print("\n===========\n")

#Part-e
print("The determinant of arr_1 is:",np.linalg.det(arr_1))
print("The determinant of arr_2 is:",np.linalg.det(arr_2))
print("The inverse of arr_1 is:",np.linalg.inv(arr_1))
print("The inverse of arr_2 is:",np.linalg.inv(arr_2))

The first array is:  [[5 3 8]
 [1 5 5]
 [4 4 9]]

The second array is:  [[6 9 4]
 [0 6 7]
 [1 8 0]]


The sum of two matrices:  [[11 12 12]
 [ 1 11 12]
 [ 5 12  9]]


The difference of two matrices:  [[-1 -6  4]
 [ 1 -1 -2]
 [ 3 -4  9]]


Matrix multiplication:
Element-wise [[30 27 32]
 [ 0 30 35]
 [ 4 32  0]]

Dot product: [[ 38 127  41]
 [ 11  79  39]
 [ 33 132  44]]


The transpose of the matrix arr_1 is: [[5 1 4]
 [3 5 4]
 [8 5 9]]
The transpose of the matrix arr_2 is: [[6 0 1]
 [9 6 8]
 [4 7 0]]


The determinant of arr_1 is: 30.000000000000004
The determinant of arr_2 is: -297.00000000000006
The inverse of arr_1 is: [[ 0.83333333  0.16666667 -0.83333333]
 [ 0.36666667  0.43333333 -0.56666667]
 [-0.53333333 -0.26666667  0.73333333]]
The inverse of arr_2 is: [[ 0.18855219 -0.10774411 -0.13131313]
 [-0.02356902  0.01346801  0.14141414]
 [ 0.02020202  0.13131313 -0.12121212]]
